HONKS token
Bitcoin-com/bch-token-icons pull request #3
Opened 2019-04-09 19:12 UTC by CollinEnstad

HONK HONK

2019-04-09 23:45 UTC, p2pcash requested changes
It needs a comma here after the } .

Also you should try to squash your commits if you can.

2019-04-09 23:46 UTC, bchWhaleClub commented on manifest.json
> +  },
You should remove this trailing comma too.

2019-04-09 23:47 UTC, bchWhaleClub commented on manifest.json
>    }
It needs a comma after the }

2019-04-09 23:47 UTC, bchWhaleClub commented
Could you also squash your commits into a single one ?

2019-04-10 00:24 UTC, CollinEnstad commented
fixed, but i have 0 idea how to squash, google doesnt help. sorry, github noob.

2019-04-14 06:14 UTC, cgcardona commented
This has been handled manually.

2019-04-14 06:14 UTC, closed without merging